linters:
  enable:
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - funlen
    - gci
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - ifshort
    - interfacer
    - lll
    - makezero
    - maligned
    - misspell
    - nakedret
    - nestif
    - prealloc
    - predeclared
    - whitespace
    - wrapcheck
    - dogsled
linters-settings:
  funlen:
    lines: 100
    statements: 50